server:
  port: 8080
datasource:
  primary:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: root
    password: 123456
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=wfs
    autoCommit: true
    #连接超时5s
    connectionTimeout:  6000
    #空闲超时时间（10分钟）
    idleTimeout:  600000
    #最大存活时间 （最好设置）默认30分钟
    maxLifetime: 1800000
    #最大连接池大小
    maximumPoolSize: 200
    minimumIdle: 5
  secondary:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: root
    password: 123456
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=common
    autoCommit: true
    #连接超时5s
    connectionTimeout:  6000
    #空闲超时时间（10分钟）
    idleTimeout:  600000
    #最大存活时间 （最好设置）默认30分钟
    maxLifetime: 1800000
    #最大连接池大小
    maximumPoolSize: 200
    minimumIdle: 5

redis.client.host:
  list:
    - {host: 127.0.0.105, port: 8001}
    - {host: 127.0.0.105, port: 8002}
    - {host: 127.0.0.105, port: 8003}
    - {host: 127.0.0.105, port: 8004}
    - {host: 127.0.0.105, port: 8005}
    - {host: 127.0.0.105, port: 8006}
redis.client.pool:
  #连接池最大实例数
  maxTotal: 200
  #最大空闲实例数
  maxIdle: 100
  #获取实例等待时间
  maxWaitMillis: 1500
  #获取实例前是否测试连接
  testOnBorrow: true

  


  






